[main]
force-persist sessions = false
# in seconds -> 7days
# how long a session is allowed to persist in the backend database
session lifetime = 60 * 60 * 24 * 7
email me = false
packages = drive

[account.profile]
# you can set a secondary email address or use your signup email address (if any) 
# to use for communications with the server 
email-address = some@email.com
# your email would not be shown in the browser configs window
# nor would the backend know it unless you use it to signin to your account.
# if `email me` is set to `true` and you didnt signin with your email address, 
# then the server would ask you for your email address everytime it sends you an email 
expose address = false

[colorschemes.manage]
current = verdant

[packages.drive]
addr = http://127.9.9.1:9898
tags = fs files download upload backup store 
color = #859f60
