[main]
force-persist sessions = false
# in seconds -> 7days
# how long a session is allowed to persist in the auth backend
session lifetime = 60 * 60 * 24 * 7
send me emails = false
packages = drive

[account.profile]
email-address = some@email.com
# your email would not be shown in the browser configs window
# the backend would not know it either unless you use it to signin
# if `send me emails` is set to `true` and you didnt signin with your address, 
# then the server would ask you for your address everytime it sends you an email 
expose email-address = false

[colorschemes.manage]
current = verdant

[packages.drive]
addr = http://127.9.9.1:9898
tags = fs files download upload backup store 
color = #859f60
